# Generated by Django 3.0.3 on 2020-03-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManage', '0002_auto_20200322_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='mail',
        ),
    ]
