# Generated by Django 3.0.3 on 2020-03-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManage', '0004_loginuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
